### ISSUE TITLE
environment without credentials causing null pointer exception

### ISSUE THREAD

**Issue by kvmw** [pivotal/cf-env#1]
Following sample env. which has null value as credentials, causes NPE in `CloudFoundryEnvironment` class.

```json
{
  "lionlogger": [
    {
      "credentials": null,
      "label": "foo-service",
      "name": "myapp-logger",
      "plan": "spider",
      "tags": [
        "Logging",
        "Cool Service",
        "Developer Tools"
      ]
    }
  ]
}
```

**Comment by Zlate87** [comment]
Any plans for creating a new release including this changes?

**Comment by kvmw** [comment]
Hi @Zlate87 

I am trying to publish a new version of this lib with different group-id. As you may probably know, we don't have access to the original bintray repo to publish it. 

Meanwhile, You should be able to use the version `0.0.2`, which includes above fix, by configuring __one of the following repositories__ in your `gradle.build`:

```
maven {
  url  "https://dl.bintray.com/ipsi/cf-env"
}
```
or 
```
maven {
  url  "https://dl.bintray.com/pivotal-kaveh/maven-repo"
}
```

and then: 
`compile ('io.pivotal.labs:cf-env:0.0.2')`

good luck.

**Comment by kvmw** [comment]
@Zlate87  the new version (`0.0.2`) is available in `jcenter` now.

**Comment by Zlate87** [comment]
@pivotal-kaveh thanks.
